### ISSUE TITLE
Dashboard error!! Please help me

### ISSUE THREAD

**Issue by LamTruong-SystemAdmin** [augustoliks/lab-opensearch#1]
I cannot access:
- Elasticsearch Dashboard with error code "Failed to upgrade legacy queries Datasource ${DS_ELASTICSEARCH_PROD_METRICS} was not found"
- Elasticsearch - Exporter has error code "Failed to upgrade legacy queries Datasource ${DS_DML-PROM0} was not found"
I use OS: Ubuntu Server 20.04

**Comment by augustoliks** [comment]
I frequently updated the files of this repository. Does the problem still exist?
